version: '3.6'
services:
  redis:
    image: ${REDIS_VERSION}
    container_name: "redis"
    volumes:
      - ./data/redis:/data
  mongodb:
    image: ${MONGODB_VERSION}
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  web:
    container_name: "webapp"
    build: ${WEB_DIR}
    depends_on: 
      - redis
    ports:
     - "5000:5000"
